//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingId { get; set; }
        public int SeatNumber { get; set; }
        public string PassengerName { get; set; }
        public string PassengerAge { get; set; }
        public string PassengerGender { get; set; }
    
        public virtual TicketBooking TicketBooking { get; set; }
    }
}
