//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusDetail
    {
        public BusDetail()
        {
            this.Buses = new HashSet<Bus>();
        }
    
        public string BusName { get; set; }
        public int BusRegistrationNumber { get; set; }
        public string BusType { get; set; }
        public decimal Fare { get; set; }
        public decimal BasePrice { get; set; }
        public int BusContactNumber { get; set; }
        public int TotalSeat { get; set; }
    
        public virtual ICollection<Bus> Buses { get; set; }
    }
}
