//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusStatu
    {
        public BusStatu()
        {
            this.SeatStatus = new HashSet<SeatStatu>();
            this.TicketBookings = new HashSet<TicketBooking>();
        }
    
        public int BusRegistrationNumber { get; set; }
        public int SeatFilled { get; set; }
        public System.DateTime Date { get; set; }
        public int RouteId { get; set; }
        public int BusStatusId { get; set; }
        public int BusTimingId { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual BusTiming BusTiming { get; set; }
        public virtual ICollection<SeatStatu> SeatStatus { get; set; }
        public virtual ICollection<TicketBooking> TicketBookings { get; set; }
    }
}
