//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusTiming
    {
        public BusTiming()
        {
            this.BusStatus = new HashSet<BusStatu>();
        }
    
        public int BusRegistrationNumber { get; set; }
        public int RouteId { get; set; }
        public System.TimeSpan StartingTime { get; set; }
        public int BusTimingId { get; set; }
    
        public virtual ICollection<BusStatu> BusStatus { get; set; }
    }
}
