//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.Queries = new HashSet<Query>();
            this.TicketBookings = new HashSet<TicketBooking>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerGender { get; set; }
        public Nullable<decimal> CustomerContactNumber { get; set; }
    
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual ICollection<Query> Queries { get; set; }
        public virtual ICollection<TicketBooking> TicketBookings { get; set; }
    }
}
