//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public Stop()
        {
            this.RouteStops = new HashSet<RouteStop>();
        }
    
        public int StopId { get; set; }
        public string StopName { get; set; }
    
        public virtual ICollection<RouteStop> RouteStops { get; set; }
    }
}
