//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBooking
    {
        public TicketBooking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.CancelBookings = new HashSet<CancelBooking>();
        }
    
        public int BookingId { get; set; }
        public int NumberOfSeat { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int BusStatusId { get; set; }
        public int PaymentId { get; set; }
        public System.DateTime DepartureDate { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual BusStatu BusStatu { get; set; }
        public virtual ICollection<CancelBooking> CancelBookings { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
